isomerpages/mlaw-corp

_about-us/6-contact-us.md, _config.yml, _data/navigation.yml, index.md, pages/contact-us.md, pages/eservices.md
Change eservices url for GCC migration on 24 Nov 2019.
=> Change of eservices url

_admission-to-the-bar/1a-admission-requirements.md
This change was made to test isomer's webhook for purging cache.
=> Added full stop on the date 

_redirects, news/speeches/_posts/2019-11-19-Speech-by-Senior-Minister-of-State-for-Law-and-Health-Mr-Edwin-Tong-at-the-Launch-of-the-PCA-Singapore-Office.md, news/speeches/_posts/2019-11-27-Speech-by-Mr-Calvin-Phua-Deputy-Secretary-Ministry-of-Law-at-the-ICLP-Forum-2019.md
=> SMS PCA Speech

news/press-releases/_posts/2019-12-27-Commencement-of-Amendments-to-the-Penal-Code-and-Other-Legislation-on-1-January-2020.md
=> Commencement of Amendments to the Penal Code and Other Legislation on 1 January 2020

news/speeches/_posts/2020-02-28-Response-Speech-by-Senior-Minister-of-State-for-Law-Edwin-Tong-at-the-Committee-of-Supply-Debate-2020-(Attorney's-General-Chambers).md
=> COS2020 SMS Speech

_covid19/01-about-the-bill.md, _data/homepage.yml
Updated text on homepage and categories under About the Bill.
=> Covid19-Relief

_law-practice-entities-and-lawyers/1b-apply-for-a-licence-or-registration-for-a-new-law-practice-entity.md, _law-practice-entities-and-lawyers/3c-submit-a-complaint-about-a-law-practice-entity.md, news/press-releases/_posts/2020-05-27-Issuance-of-Directions-under-POFMA-to-National-Times-Singapore-Facebook-Page-and-Facebook.md
As per my email dated 27 May 2020, I have updated the links below: 
Line 241 - LSRA e-Services Portal link
Line 229 - complaint link
=> updated the broken links

_law-practice-entities-and-lawyers/1b-apply-for-a-licence-or-registration-for-a-new-law-practice-entity.md
updated link to be a pop-up window
=> updated link to be a pop-up window in step 5

_law-practice-entities-and-lawyers/1e-terminate-the-licence-or-registration-of-a-law-practice-entity.md, _law-practice-entities-and-lawyers/1f-approval-to-share-premises.md, _law-practice-entities-and-lawyers/2b-register-an-individual.md, _law-practice-entities-and-lawyers/2c-update-the-particulars-of-an-individual.md, _law-practice-entities-and-lawyers/3a-apply-for-approval-to-hold-interests-in-a-law-practice-entity.md, _law-practice-entities-and-lawyers/3b-request-for-a-certificate-of-good-standing.md, _law-practice-entities-and-lawyers/4b-useful-template.md, _law-practice-entities-and-lawyers/4c-relevant-organisations.md
As per email of 18 March 2020 on "Broken links in LID/LSRA website".
=> Broken links and pop-up windows

_law-practice-entities-and-lawyers/1b-apply-for-a-licence-or-registration-for-a-new-law-practice-entity.md, _law-practice-entities-and-lawyers/1c-update-the-particulars-of-a-law-practice-entity.md
(1) Licensing or Registration of Law Practice Entities > Update Particulars of a Law Practice Entity >Step 3
(2) Licensing or Registration of Law Practice Entities > Apply for a Licence or Registration for a New Law Practice Entity > Step 3
=> 2 updates as per email of 12 June 2020

news/parliamentary-speeches/_posts/2020-11-03-Second-Reading-Speech-by-2M-Edwin-Tong-on-the-COVID-19-Temporary-Measures-Amendment-Bill-and-IRDA.md
…-19-Temporary-Measures-Amendment-Bill-and-IRDA.md
=> Updated 2R speech

_covid19/02-D-Hire-purchase-agreements.md, _covid19/02-E-Rental-agreements.md, _covid19/02-G-Event-or-tourism-related-contracts.md
To update after expiry of prescribed period on 31 Jan 2021.
=> Updates to events, hire-purchase and rental agreement page.

_realign/2-process-Renegotiation.md
=> update 2. RAF form 6 2Mar 0000

news/public-consultations/_posts/2021-02-05-public-consultation-proposed-copyright-bill.md
Updated consultation period for the public consultation on the proposed Copyright Bill to reflect one-week extension
=> Updated consultation period due to extension

news/parliamentary-speeches/_posts/2021-05-10-Oral-Answer-by-Minister-for-Law-Mr-K-Shanmugam-to-Publishing-Names-Of-Accused-Persons.md
…ublishing-Names-Of-Accused-Persons.md
=> Oral-Answer-by-Minister-for-Law-Mr-K-Shanmugam

news/press-releases/_posts/2021-08-02-First-Reading-Of-Criminal-Law-Miscellaneous-Amendments-Bill.md
=> First Reading Of Criminal Law (Amd) Bill

news/speeches/_posts/2021-12-15-Speech-by-Edwin-Tong-International-Commercial-and-Legal-Cooperation-Forum-2021.md
…egal-Cooperation-Forum-2021.md
=> Upload 2M's speech at ICLC 2021

news/parliamentary-speeches/_posts/2022-01-10-Written-Answer-by-Minister-for-Law-Mr-K-Shanmugam-to-PQ-on-Number-of-Debtors-Committed-by-Court-to-Civil-Prison-under-Section-6-1-6-3-or-15-1-of-Debtors-Act-in-Past-10-Years.md
…o-PQ-on-Number-of-Debtors-Committed-by-Court-to-Civil-Prison-under-Section-6-1-6-3-or-15-1-of-Debtors-Act-in-Past-10-Years.md
=> Written PQ response on Debtors Act

pages/eservices.md
to update eservices page. remove past maintenace message.
=> Update file: eservices.md

pages/eservices.md
Update maintenance notice for CRM applications
=> Update file: eservices.md for CRM applications

_about-us/contact-us.md, pages/eservices.md
=> Update file: contact-us.md

_about-us/contact-us.md
extension of Online Enquiry maintenance
=> extension of Online Enquiry maintenance

_about-us/contact-us.md, news/public-consultations/_posts/2022-11-03-post-CMO public consultation.md, pages/eservices.md
Update ecrm maintenance notice
=> Update ecrm maintenance notice

news/press-releases/_posts/2022-11-07-post-MinLaw & IPOS Seek Feedback on Subsidiary Legislation on Regulation of CMOs.md, news/public-consultations/_posts/2022-11-07-post-Public Consultation on Draft Regulations for Collective Management Organisations.md
=> Edit email Link

_about-us/contact-us.md, pages/eservices.md
Vani requested further changes to eservice page and contact us page.
=> Update contact us and eservice page as requested by Vani

_about-us/contact-us.md, pages/eservices.md
Removing old maintenance message as per Vani's request
=> Removing old maintenance message

_about-us/contact-us.md
=> Update maintenance notice

_about-us/contact-us.md, news/speeches/_posts/2022-11-21-post-Speech by Minister for Home Affairs and Law K Shanmugam at the Judicial Executive Programme 2022.md, pages/eservices.md
I have amended eServices and Contact Us page for publishing maintenance message starts from 25th Mar 2 pm to 26th Mar 8 pm.
=> Update on eServices and Contact Us page for maintenance message

_about-us/contact-us.md, news/press-releases/_posts/2023-03-31-post-Official Visit to Xiamen by Minister Edwin Tong SC.md, pages/eservices.md
Update Contact Us Page and eServices for Monthly Maintenance
=> Monthly Maintenance message

news/press-releases/_posts/2023-04-24-post-Singapore and Shanghai Sign a MOU to Deepen Legal Cooperation.md, pages/eservices.md
Maintenance message for CRM Applications
=> Publish Maintenance Message for CRM Applications

pages/eservices.md
=> Update Maintenance message

pages/eservices.md
=> IPTO downtime

pages/eservices.md
=> Edit Maintenace Message

pages/eservices.md
=> For weekend downtime since GCC will be down when they do patching

pages/eservices.md
=> remove maint msg

pages/eservices.md
Commented on Maintenance message so that it is not viisble to MoP and in case if required to publish again
=> Hide maintenance message from MoP

pages/eservices.md
=> Update eservices.md sw testing on mobile

pages/eservices.md
=> remove maintenance message

pages/eservices.md
=> Urgent Maintenance for CRM

_about-us/contact-us.md
=> Update maintenance message under contact us

pages/eservices.md
=> maintenance timing

pages/eservices.md
=> maintenance msg

pages/eservices.md
=> maintenance message

pages/eservices.md
=> urgent maint

pages/eservices.md
=> edit maint msg

pages/eservices.md
Those who like to verify during review on approval process may refer to
1. Source code comparison
2. Staging site
Assume Reviewer will be doing merging action as well.
=> Remove urgent maintenance notice

news/speeches/_posts/2023-07-27-post-Keynote Speech By Minister K Shanmugam At Conference: Empowering Women Through Gamechanging.md, pages/eservices.md
1. eServices updates for maintenance downtime
=> Several updates by different people. 

pages/eservices.md
=> pto cims drs

_about-us/What We Do/legal-policy-group.md, pages/eservices.md
…icy-group.md","userId":"252"}
=> Updating Legal Policy Group What we do page

_data/footer.yml, pages/eservices.md
=> Remove LID maintenance msg

pages/eservices.md
=> Update Maintenance message for CMU and LSRA

pages/eservices.md
=> Remove maintenance msg for CMU and LSRA

_about-us/contact-us.md
=> maintenance message for contact centre

_about-us/contact-us.md
=> Remove maintenance msg for Contact Centre

pages/eservices.md
=> maint message

_about-us/contact-us.md
=> MSC closure notice

_about-us/contact-us.md
=> Removing closure notice

pages/eservices.md
=> Publish Maintenance Message for Weekend monthly Patching activity

_about-us/What We Do/legal-industry-division.md
=> update LID page

_data/navigation.yml, index.md
=> pull request at 5.18pm

_about-us/Contact Us.md
=> Removing MSC closure notice

index.md
=> update SCW 2023 to SCW 2024

news/speeches/_posts/2024-05-24-post-Speech by Minister for Culture, Community and Youth, Mr Edwin Tong SC, at Tri AGC event.md, pages/eservices.md
Note: have checked with Vani from ITD on her changes- she affirmed it is good to go.
=> 2M's speech at tri-agc

_trusts/Express Trusts.md, _trusts/Trusts and Trust Like Arrangements in Singapore.md, pages/eservices.md
=> Update Trusts Website v2

_about-us/Contact Us.md
=> Update LSRA under live chat for contact us page

pages/eservices.md
Removed previous downtime message.
=> Updated eServices

pages/eservices.md
6 Sep 5pm to 9 Sep 8am production downtime
=> CAS2 production rollout

pages/eservices.md
Downtime requested is the same : Sat 14 Sep 2pm to Mon 16 8am.
=> DC servers upgrade@14 Sep

pages/eservices.md
added more systems as Ivy requested on 13 Sep
=> DC Server Upgrade@14 Sep

pages/eservices.md
=> Remove 14 Sep downtime msg

pages/eservices.md
=> DR exercise@4 Oct

pages/eservices.md
=> DC DR Trial Swing@12 to 14 Oct

_about-us/Contact Us.md
Closure notice and amendments to VC with servicesg
=> Update for contact us page

pages/eservices.md
=> GCC DR@2 Nov, DC DR@16Nov

pages/eservices.md
=> Update maintenance schedule

_about-us/Contact Us.md
=> Adding additional domain for live chat

pages/eservices.md
=> Publish downtime for ROMP for GB migration

pages/eservices.md
=> sntc downtime

pages/eservices.md
MLAW PROD Patching - [November-24 Release]|
=> MLAW PROD Patching - [November-24 Release]| 

_about-us/Contact Us.md
=> Posting closure notice

pages/eservices.md
20 to 23 Dec: Combined Tender KTA/Decisions upgrade
=> 20 to 23 Dec: Combined Tender KTA/Decisions upgrade

pages/Career Opportunities.md, pages/MinLaw Internship Programme.md, pages/Why Join MinLaw.md, pages/eservices.md
Maintenance Page for eServices
=> Maintenance Page for eServices

_about-us/Contact Us.md
=> Adding MED under live chat

pages/eservices.md
=> Update maintenance msg

pages/eservices.md
=> Maintenance Msg update

_about-us/Contact Us.md
=> Remove closure notice

_about-us/Contact Us.md, index.md, pages/eservices.md
=> Update closure notice

pages/eservices.md
Monthly patching 10May 2pm to 12May 8am
=> Monthly patching 10May 2pm to 12May 8am

pages/eservices.md
Start: Saturday, 28 June 2025, 2:00 PM
End: Monday, 30 June 2025, 8:00 AM
=> Combined Tender - TA Upgrade: System Downtime Notice

_law-practice-entities-and-lawyers/Resources for Law Practice Entities/relevant-legislation-and-communications.md, pages/eservices.md
The scheduled downtime is from 11 July 2025, Friday 06:00pm to 14 July 2024, Monday, 08:00am.
=> ICMP Pega Upgrade

_about-us/Contact Us.md
=> Closure notice

_law-practice-entities-and-lawyers/Licensing Or Registration Of Law Practice Entities/apply-for-a-licence-or-registration-for-a-new-law-practice-entity.md, _law-practice-entities-and-lawyers/Licensing Or Registration Of Law Practice Entities/renew-the-licence-of-a-law-practice-entity.md, _law-practice-entities-and-lawyers/Licensing Or Registration Of Law Practice Entities/terminate-the-licence-or-registration-of-a-law-practice-entity.md, _law-practice-entities-and-lawyers/Licensing Or Registration Of Law Practice Entities/types-of-licence-or-registration.md, _law-practice-entities-and-lawyers/Licensing Or Registration Of Law Practice Entities/update-the-particulars-of-a-law-practice-entity.md, _law-practice-entities-and-lawyers/Other Services/apply-for-approval-to-hold-interests-in-a-law-practice-entity.md, _law-practice-entities-and-lawyers/Other Services/request-a-certificate-of-good-standing.md, _law-practice-entities-and-lawyers/Registration of Individuals/register-an-individual.md, _law-practice-entities-and-lawyers/Registration of Individuals/terminate-the-registration-of-an-individual.md, _law-practice-entities-and-lawyers/Registration of Individuals/update-the-particulars-of-an-individual.md
Updated: (a) “Applications that are…” to reflect the complex definition and the “peak period from January to March…” to “December to April”, (b) “Last Update…” and (c) other necessary points.
=> Updated the processing timeline and peak period

pages/eservices.md
23 August 2025 (Sat) 1400 hrs to 25 August 2025 (Mon) 0800 hrs
=> DR dry run on 23-25 Aug

pages/eservices.md
6 September 2025 (Sat) 0000 hrs to 7 September 2025 (Sun) 1800 hrs
=> September 2025 monthly patching

pages/eservices.md
DR Exercise, 20 Sep 2025 (Sat), 7 am – 22 Sep 2025 (Mon), 8 am
=> DR Exercise, 20 Sep 2025 (Sat), 7 am – 22 Sep 2025 (Mon), 8 am

pages/eservices.md
4 October 2025 (Sat) 0000 hrs to 5 October 2025 (Sun) 2359 hrs
=> Oct Mthly Maintenance - update end time
